apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus

  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009
    editable: true
    uid: mimir
    jsonData:
      timeInterval: "15s"

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    uid: loki
    jsonData:
      derivedFields:
        - name: "traceID"
          matcherRegex: "traceID=(\\w+)"
          url: "${__value.raw}"
          datasourceUid: "tempo"

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToMetrics:
        enabled: true
        datasourceUid: 'prometheus'
      tracesToProfiles:
        enabled: true
        datasourceUid: 'pyroscope'
      tracesToLogs:
        datasourceUid: 'loki'
        #        tags: [ 'job', 'instance', 'pod', 'namespace' ]
        mappedTags: [ { key: 'service.name', value: 'service' } ]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
      serviceMap:
        datasourceUid: 'prometheus'

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    editable: true
    uid: pyroscope
    jsonData:
      httpMethod: GET