global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Remote write configuration for long-term storage in Mimir
remote_write:
  - url: "http://mimir:9009/api/v1/push"
    name: mimir
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_shards: 200
      min_shards: 1
      max_samples_per_send: 2000
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 100ms

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
#  - job_name: 'tempo'
#    static_configs:
#      - targets: [ 'tempo:3200' ]
#  - job_name: 'loki'
#    static_configs:
#      - targets: [ 'loki:3100' ]
#  - job_name: 'alloy'
#    static_configs:
#      - targets: [ 'alloy:12345' ] # Ensure Alloy exposes metrics on this port