/*
 * Copyright (c) 2025 Karlsruhe Institute of Technology
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package edu.kit.datamanager.idoris.rules.logic;

import io.micrometer.core.annotation.Counted;
import io.micrometer.core.annotation.Timed;
import io.micrometer.observation.annotation.Observed;
import io.opentelemetry.api.trace.SpanKind;
import io.opentelemetry.instrumentation.annotations.SpanAttribute;
import io.opentelemetry.instrumentation.annotations.WithSpan;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.ListableBeanFactory;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Supplier;
import java.util.stream.Collectors;

@Component
@RequiredArgsConstructor
@Slf4j
@Observed(contextualName = "ruleService")
public class RuleService implements IRuleService {

    /**
     * Provides access to all Spring-managed beans for rule discovery.
     * <p>
     * Used to selectively load only the rule implementations that are actually referenced
     * in the precomputed dependency graph, avoiding the instantiation of unused rules.
     */
    private final ListableBeanFactory beanFactory;
    /**
     * Thread-safe registry mapping fully qualified class names to rule instances.
     * <p>
     * This registry serves as a cache of rule implementations that have been loaded from the
     * Spring context. It uses the fully qualified class name as the key since that's what
     * the precomputed graph uses to identify rules. The {@link ConcurrentHashMap} implementation
     * ensures thread safety during concurrent rule execution.
     */
    private final Map<String, IRule<?, ?>> ruleRegistry = new ConcurrentHashMap<>();

    /**
     * The precomputed rule dependency graph loaded from generated code.
     * <p>
     * This graph contains the topologically sorted rule class names for each combination of
     * rule task and target element type. It's generated at compile-time by the annotation
     * processor, eliminating the need for runtime dependency analysis. The graph is the
     * authoritative source for rule execution order.
     */
    private PrecomputedRuleGraph precomputedGraph;

    /**
     * Initializes the rule engine by loading the precomputed dependency graph and
     * discovering required rule implementations.
     * <p>
     * This method follows a two-step initialization process:
     * <ol>
     *   <li>First, it loads the precomputed rule dependency graph from the generated implementation</li>
     *   <li>Then, it selectively loads only the rule implementations that are referenced in the graph</li>
     * </ol>
     * <p>
     * This approach ensures that only rules that are actually needed are instantiated, reducing
     * memory usage and startup time. It also allows the rule engine to provide detailed diagnostic
     * information about missing rules at startup rather than failing at runtime.
     * <p>
     * This method is automatically called by Spring after dependency injection is complete.
     *
     * @throws IllegalStateException if the rule engine initialization fails, either because
     *                               the precomputed graph couldn't be loaded or because critical
     *                               rule implementations are missing
     */
    @PostConstruct
    void initialize() {
        try {
            // Load precomputed graph first to know which rules we need
            loadPrecomputedGraph();

            // Only discover rules that are actually referenced in the precomputed graph
            discoverRequiredRules();

            log.info("Rule engine initialized with {} rules", ruleRegistry.size());
        } catch (Exception e) {
            log.error("Failed to initialize rule engine", e);
            throw new IllegalStateException("Rule engine initialization failed", e);
        }
    }

    /**
     * Loads the precomputed rule dependency graph from generated code.
     * <p>
     * This method uses reflection to instantiate the implementation class of {@link PrecomputedRuleGraph}
     * that was generated by the annotation processor at compile time. The generated class contains
     * the complete dependency information for all rules, including their topological sorting.
     * <p>
     * The precomputed graph is the source of truth for rule execution order and is used to:
     * <ul>
     *   <li>Determine which rule implementations need to be loaded from Spring</li>
     *   <li>Determine the correct execution order of rules for each task and element type</li>
     *   <li>Optimize rule execution by enabling parallel processing where possible</li>
     * </ul>
     *
     * @throws IllegalStateException if the precomputed graph implementation cannot be loaded,
     *                               which could happen if the annotation processor didn't run
     *                               or if the generated class is not on the classpath
     */
    @WithSpan(kind = SpanKind.INTERNAL)
    private void loadPrecomputedGraph() {
        log.info("Loading precomputed rule dependency graph...");

        try {
            // Load the generated implementation class
            Class<?> implClass = Class.forName("edu.kit.datamanager.idoris.rules.logic.PrecomputedRuleGraphImpl");
            precomputedGraph = (PrecomputedRuleGraph) implClass.getConstructor().newInstance();

            log.info("Precomputed rule graph loaded successfully");
        } catch (Exception e) {
            log.error("Failed to load precomputed rule graph", e);
            throw new IllegalStateException("Precomputed rule graph not available", e);
        }
    }

    /**
     * Discovers and registers only the rule beans that are referenced in the precomputed graph.
     * <p>
     * This method implements a key optimization in the rule engine: it only loads rule
     * implementations that are actually needed based on the precomputed graph. This approach
     * significantly reduces memory usage and startup time, especially in large systems with
     * many rule implementations where only a subset might be used for specific tasks.
     * <p>
     * The method works in three steps:
     * <ol>
     *   <li>Extract all unique rule class names from the precomputed graph</li>
     *   <li>Query the Spring context for all {@link IRule} implementations</li>
     *   <li>Register only those rule implementations that are referenced in the graph</li>
     * </ol>
     * <p>
     * Additionally, this method provides diagnostic information about missing rules, which
     * can help identify configuration issues early during application startup rather than
     * failing at runtime.
     */
    @WithSpan(kind = SpanKind.INTERNAL)
    private void discoverRequiredRules() {
        log.info("Discovering required rule implementations...");

        // Extract all unique rule class names from the precomputed graph and track their discovery status
        // This creates a map where keys are class names and values are booleans indicating if they've been found
        Map<String, Boolean> requiredRuleClasses = precomputedGraph.getSortedRulesByTaskAndType()
                .values()                                // Get all target type maps
                .stream()                                // Stream the maps
                .flatMap(targetTypeMap -> targetTypeMap.values().stream())  // Flatten to all rule lists
                .flatMap(List::stream)                  // Flatten to individual rule class names
                .collect(Collectors.toMap(
                        className -> className,          // Key is the class name
                        className -> false,             // Initial value false (not yet found)
                        (existing, replacement) -> existing  // Keep existing entry on duplicate key
                ));

        log.debug("Precomputed graph references {} unique rule classes", requiredRuleClasses.size());

        // Find and register only the required rule beans
        beanFactory.getBeansOfType(IRule.class)
                .forEach((beanName, ruleBean) -> {
                    String className = ruleBean.getClass().getName();

                    // Only register if this rule is referenced in the precomputed graph
                    if (requiredRuleClasses.containsKey(className)) {
                        ruleRegistry.put(className, ruleBean);
                        requiredRuleClasses.put(className, true); // mark as found
                        log.debug("Registered required rule: {}", className);
                    } else {
                        log.debug("Skipping unreferenced rule: {}", className);
                    }
                });

        // Log any missing rules
        long missingRules = requiredRuleClasses.values().stream()
                .mapToLong(found -> found ? 0 : 1)
                .sum();

        if (missingRules > 0) {
            log.warn("{} rules referenced in precomputed graph were not found in Spring context", missingRules);

            if (log.isDebugEnabled()) {
                requiredRuleClasses.entrySet().stream()
                        .filter(entry -> !entry.getValue())
                        .forEach(entry -> log.debug("Missing rule: {}", entry.getKey()));
            }
        }

        log.info("Discovered {} required rule implementations", ruleRegistry.size());
    }

    /**
     * Executes all applicable rules for the given task and element.
     * <p>
     * This method is the primary entry point for rule execution. It retrieves the correct
     * sequence of rules from the precomputed graph based on the task and element type,
     * then executes them sequentially while maintaining OpenTelemetry span context.
     * <p>
     * The method follows these steps:
     * <ol>
     *   <li>Identify the correct set of rule class names from the precomputed graph</li>
     *   <li>Execute those rules sequentially in their dependency order</li>
     *   <li>Merge the results from all rules into a single result object</li>
     * </ol>
     * <p>
     * If no rules are found for the given task and element type, an empty result is returned.
     * <p>
     *
     * @param task          the rule task to execute (e.g., {@link RuleTask#VALIDATE})
     * @param element       the domain element to process
     * @param resultFactory factory for creating result objects (typically a constructor reference)
     * @param <T>           element type extending {@link VisitableElement}
     * @param <R>           result type extending {@link RuleOutput}
     * @return the merged result of all executed rules, or an empty result if no rules apply
     * @throws RuntimeException if a critical error occurs during rule execution that prevents
     *                          completion of the operation
     */
    @WithSpan(kind = SpanKind.INTERNAL)
    @Timed(value = "rules.ruleService.executeRules", description = "Time to execute all rules for a given task/element", histogram = true)
    @Counted(value = "rules.ruleService.executeRules.count", description = "Rule execution entrypoints")
    public <T extends VisitableElement, R extends RuleOutput<R>> R executeRules(
            @SpanAttribute RuleTask task,
            T element,
            Supplier<R> resultFactory
    ) {
        String elementType = element.getClass().getName();
        log.debug("Executing rules for task={}, elementType={}", task, elementType);

        // Get sorted rule class names directly from precomputed graph
        List<String> ruleClassNames = precomputedGraph.getSortedRuleClasses(task, elementType);

        if (ruleClassNames.isEmpty()) {
            log.debug("No rules found for task={}, elementType={}", task, elementType);
            return resultFactory.get();
        }

        log.debug("Found {} rules for task={}, elementType={}", ruleClassNames.size(), task, elementType);

        // Execute rules sequentially to maintain proper dependency order and OpenTelemetry context
        return executeRulesSequentially(ruleClassNames, element, resultFactory);
    }

    @WithSpan(kind = SpanKind.INTERNAL)
    @Override
    public <T extends VisitableElement, R extends RuleOutput<R>> R executeSpecificRule(String ruleName, T element, Supplier<R> resultFactory) throws RuntimeException {
        return executeRulesSequentially(List.of(ruleName), element, resultFactory);
    }

    @WithSpan(kind = SpanKind.INTERNAL)
    @Override
    public <T extends VisitableElement, R extends RuleOutput<R>> R executeSpecificRule(IRule<T, R> rule, T element, Supplier<R> resultFactory) throws RuntimeException {
        return executeRule(rule, element, resultFactory);
    }

    /**
     * Executes rules sequentially in their precomputed ordering.
     * <p>
     * This method is responsible for the sequential execution of rules. It takes the
     * list of rule class names in their precomputed execution order, retrieves the rule
     * instances from the registry, and executes them one by one while maintaining
     * the OpenTelemetry span context.
     * <p>
     * Key aspects of this implementation:
     * <ul>
     *   <li><strong>Selective execution</strong>: Only rules that are found in the registry are executed</li>
     *   <li><strong>Sequential processing</strong>: Each rule executes in order, maintaining span context</li>
     *   <li><strong>Result accumulation</strong>: Results from all rules are merged into a single result</li>
     * </ul>
     * <p>
     * If no rule instances are available for execution, an empty result is returned. This ensures
     * that the method always returns a valid result object even if no rules are executed.
     *
     * @param ruleClassNames the list of rule class names in execution order
     * @param element        the domain element to process
     * @param resultFactory  factory for creating result objects
     * @param <T>            element type extending VisitableElement
     * @param <R>            result type extending RuleOutput
     * @return the merged result of all executed rules
     * @throws RuntimeException if rule execution fails critically
     */
    @SuppressWarnings("unchecked")
    @WithSpan(kind = SpanKind.INTERNAL)
    private <T extends VisitableElement, R extends RuleOutput<R>> R executeRulesSequentially(
            @SpanAttribute List<String> ruleClassNames,
            T element,
            Supplier<R> resultFactory
    ) {
        R finalResult = resultFactory.get();

        for (String ruleClassName : ruleClassNames) {
            IRule<?, ?> rule = getRuleFromRegistry(ruleClassName);
            if (rule != null) {
                try {
                    R ruleResult = executeRule(rule, element, resultFactory);
                    finalResult = finalResult.merge(ruleResult);
                } catch (Exception e) {
                    log.error("Rule {} execution failed: {}", rule.getClass().getSimpleName(), e.getMessage(), e);
                    throw new RuntimeException("Rule execution failed: " + e.getMessage(), e);
                }
            }
        }

        return finalResult;
    }

    /**
     * Retrieves a rule from the registry by its class name.
     * Logs a debug message if the rule is not found.
     *
     * @param ruleClassName the fully qualified class name of the rule
     * @return the rule instance, or null if not found
     */
    private IRule<?, ?> getRuleFromRegistry(String ruleClassName) {
        IRule<?, ?> rule = ruleRegistry.get(ruleClassName);
        if (rule == null) {
            log.debug("Skipping rule not found in registry: {}", ruleClassName);
        }
        return rule;
    }

    /**
     * Executes a single rule synchronously and returns its result.
     * <p>
     * This method handles the lifecycle of rule execution including:
     * <ul>
     *   <li>Creating a fresh result object for the rule</li>
     *   <li>Safely casting the rule to the correct parameterized type</li>
     *   <li>Invoking the rule's processing logic</li>
     *   <li>Capturing and handling any exceptions that occur during execution</li>
     * </ul>
     * <p>
     * The type casting in this method is safe because the precomputed graph ensures that
     * rules are only invoked with compatible element and result types. The {@code @SuppressWarnings}
     * annotation is used to silence the compiler warning about this cast.
     *
     * @param rule          the rule implementation to execute
     * @param element       the domain element to process
     * @param resultFactory factory for creating result objects
     * @param <T>           element type extending VisitableElement
     * @param <R>           result type extending RuleOutput
     * @return the rule's execution result
     */
    @SuppressWarnings("unchecked")
    @WithSpan(value = "rule.execute", kind = SpanKind.INTERNAL)
    private <T extends VisitableElement, R extends RuleOutput<R>> R executeRule(
            @SpanAttribute("rule.class") IRule<?, ?> rule,
            @SpanAttribute("element.class") T element,
            Supplier<R> resultFactory
    ) throws IllegalArgumentException {
        Rule annotation = rule.getClass().getAnnotation(Rule.class);

        if (annotation == null) throw new IllegalArgumentException("Provided rule is not annotated with @Rule");

        log.debug("Executing rule {} for element of type {}", annotation.name(), element.getClass().getName());

        // Check if the rule applies to the element type
        if (Arrays.stream(annotation.appliesTo())
                .anyMatch(appliesTo -> appliesTo.equals(element.getClass()))) {
            R result = resultFactory.get();

            // Perform a type-safe cast to the specific generic parameter types needed for this rule execution
            // This cast is guaranteed to be safe because the precomputed graph ensures type compatibility
            IRule<T, R> typedRule = (IRule<T, R>) rule;

            // Execute the rule's processing logic with the input element and result container
            typedRule.process(element, result);
            log.debug("Rule {} execution completed successfully", annotation.name());
            return result;
        }
        // Rule does not apply to the element type, throw an exception
        throw new IllegalArgumentException("Provided rule " + annotation.name() + " does not apply to element of type " + element.getClass().getName());
    }

}